import React, { useEffect } from 'react';
import { useForm } from '../../../context/FormContext';
import { InputField } from '../../ui/FormElements';

export const Section1_ProjectTitle: React.FC = () => {
  const { formData, updateSection } = useForm();
  const data = formData.section1 || { projectId: '', projectTitle: '' };

  useEffect(() => {
    if (!data.projectId) {
      const generatedId = `PRJ-${Math.floor(100000 + Math.random() * 900000)}`;
      updateSection('section1', { projectId: generatedId });
    }
  }, [data.projectId, updateSection]);

  const handleChange = (value: string) => {
    updateSection('section1', { projectTitle: value });
  };

  return (
    <div className="space-y-6">
      <div className="card shadow-sm">
        <div style={{ maxWidth: '800px' }} className="space-y-6">
        

          <InputField 
            label="[PC-N-1.1] Full Project Title" 
            placeholder="Enter the complete name/title of the project..."
            value={data.projectTitle}
            onChange={(e: any) => handleChange(e.target.value)}
          />
            <InputField 
            label="[PC-N-1.2] System Generated Project ID" 
            value={data.projectId}
            readOnly
            description="This ID is automatically generated by the system and cannot be edited."
            style={{ backgroundColor: 'hsl(var(--bg-main) / 0.5)', cursor: 'not-allowed' }}
          />
        </div>
      </div>
    </div>
  );
};

