export const FORM_SECTIONS = [
  { id: 1, title: 'Project Overview & Basic Information' },
  { id: 2, title: 'Cost & Approval Details' },
  { id: 3, title: 'Location & Responsibilities' },
  { id: 4, title: 'Funding & Allocation' },
  { id: 5, title: 'Project Objectives' },
  { id: 6, title: 'Description & Justification' },
  { id: 7, title: 'Cost Estimation' },
  { id: 8, title: 'Annual Operating Cost' },
  { id: 9, title: 'Demand & Supply Analysis' },
  { id: 10, title: 'Financial Plan & Mode of Financing' },
  { id: 11, title: 'Project Benefits & Analysis' },
  { id: 12, title: 'Implementation Schedule' },
  { id: 13, title: 'Management Structure & Manpower' },
  { id: 14, title: 'Additional Projects / Decisions Required' },
  { id: 15, title: 'Certificate' },
  { id: 16, title: 'Initial Scrutiny Checklist' },
  { id: 17, title: 'Relation With Other Projects' },
  { id: 18, title: 'Project Appraisal and Documentation' }
];
